[project]
name = "passphrase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=8.30.0",
    "typer>=0.15.1",
    "wordfreq>=3.1.1",
]
